//     This code was generated by a tool.
        /// </summary>
//     This code was generated by a tool.
            }
                resourceCulture = value;
//     This code was generated by a tool.
        /// </summary>
//     This code was generated by a tool.
            }
//     the code is regenerated.
        /// </summary>
        /// </summary>
// </auto-generated>
        /// </summary>
            }
        /// </summary>
        /// </summary>
        /// </summary>
        /// </summary>
//     This code was generated by a tool.
        /// </summary>
        /// </summary>
        /// </summary>
            }
        /// </summary>
//     This code was generated by a tool.
//     This code was generated by a tool.
        }
        }

        /// </summary>
//     This code was generated by a tool.
//     This code was generated by a tool.
        }
        /// </summary>
        }
        /// </summary>
        /// </summary>
//     This code was generated by a tool.
            }
//     This code was generated by a tool.
        /// </summary>
        }
                resourceCulture = value;
// </auto-generated>
//     This code was generated by a tool.
        }
//     This code was generated by a tool.
        /// </summary>
        }
        /// </summary>
//     This code was generated by a tool.
        }
        /// </summary>
            }
        /// </summary>
        /// </summary>
        /// </summary>
            }
        /// </summary>
        }
        /// </summary>
//     the code is regenerated.