                resourceCulture = value;
        }

        /// </summary>
// </auto-generated>
        }
        }
        }

                resourceCulture = value;
// </auto-generated>
        internal static global::System.Resources.ResourceManager ResourceManager {
//     This code was generated by a tool.
        }
//     This code was generated by a tool.

//     This code was generated by a tool.
        }
        internal static global::System.Resources.ResourceManager ResourceManager {


// </auto-generated>
//     This code was generated by a tool.
//     This code was generated by a tool.

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//     This code was generated by a tool.


        internal static global::System.Resources.ResourceManager ResourceManager {
// </auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//     This code was generated by a tool.
//     This code was generated by a tool.
        }
// </auto-generated>
        }
        }
//     This code was generated by a tool.
                if (object.ReferenceEquals(resourceMan, null)) {
        /// </summary>
        /// </summary>
                if (object.ReferenceEquals(resourceMan, null)) {
        }
        }
        }
        }
        }

//     This code was generated by a tool.
        }
        }

//     This code was generated by a tool.
                if (object.ReferenceEquals(resourceMan, null)) {
        internal static global::System.Resources.ResourceManager ResourceManager {
//     This code was generated by a tool.
            }

                resourceCulture = value;

//     the code is regenerated.