//     This code was generated by a tool.


    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
    }
//     Changes to this file may cause incorrect behavior and will be lost if
    }
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
//------------------------------------------------------------------------------



    }
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//     This code was generated by a tool.
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {


//     Changes to this file may cause incorrect behavior and will be lost if
        public static Settings Default {
        public static Settings Default {
                return defaultInstance;
            }
//     Changes to this file may cause incorrect behavior and will be lost if
//     This code was generated by a tool.
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {