//     This code was generated by a tool.



    }
        public static Settings Default {
    }
    }
//     This code was generated by a tool.



    }
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//     This code was generated by a tool.
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
        public static Settings Default {
    }
                return defaultInstance;
            }
        public static Settings Default {
//     This code was generated by a tool.