    }

        public static Settings Default {
        public static Settings Default {
    }
        public static Settings Default {
    }
    }

//     This code was generated by a tool.
        public static Settings Default {

    }
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public static Settings Default {
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

    }

        public static Settings Default {
        public static Settings Default {
                return defaultInstance;

        public static Settings Default {
    }